Fix panic to avoid warning message
This avoids the following error message on gleam v1.2.1.

```
warning: Panic used as a function
  ┌─ /Users/kevinrobell/Desktop/other/Coding/Projects/persistent_regex/bench/build/packages/gleamy_bench/src/gleamy/bench.gleam:9:9
  │
9 │   panic("not implemented")
  │         ^^^^^^^^^^^^^^^^^

`panic` is not a function and will crash before it can do anything with
this argument.

Hint: if you want to display an error message you should write
`panic as "my error message"`
See: https://tour.gleam.run/advanced-features/panic/
```

The other changes are just because `gleam format` now sorts imports alphabetically.